/* Bit-exactness check for the .NET Random port.
 *
 * Ground truth generated by mono itself (the same runtime that hosts the
 * reference MOLE), printed with "R" round-trip formatting so no precision is
 * lost in the comparison. Regenerate with:
 *   mcs -out:rngref.exe rngref.cs && mono rngref.exe   (rngref.cs: the C#
 *   oracle transcribing MOLE's own RNG; archived in the data deposit)
 */
#include <stdio.h>
#include <string.h>
#include "mole_rng.h"

static const char *EXPECT[20] = {
    "0.72624326996795985",  "0.81732535959096875",  "0.76802268939466345",
    "0.5581611914365372",   "0.2060331540210327",   "0.55888479461841511",
    "0.90602706601192573",  "0.44217787331071584",  "0.97754975314137982",
    "0.27370445768987034",  "0.29190628476995334",  "0.46731470034798361",
    "0.63265907281667877",  "0.46951187842968473",  "0.98215125314060192",
    "0.030366990729406004", "0.86237015382497118",  "0.99534708121574811",
    "0.67718114921691885",  "0.31459179302425672"
};
/* The 12000th draw, well past any atom count we will use, to catch drift that
   the first 20 would hide. */
static const char *EXPECT_12000 = "0.631414546925302";

int main(void)
{
    mole_rng r;
    int i, bad = 0;
    char got[64];
    double v = 0;

    mole_rng_init(&r, 0);
    for (i = 0; i < 20; i++) {
        v = mole_rng_next_double(&r);
        snprintf(got, sizeof got, "%.17g", v);
        if (strcmp(got, EXPECT[i]) != 0) {
            /* %.17g always round-trips a double, but .NET's "R" prints the
               shortest round-tripping form, so a mismatch here may be spelling
               rather than value - compare as numbers before failing. */
            double want; sscanf(EXPECT[i], "%lf", &want);
            if (want != v) { printf("  FAIL draw %d: got %s want %s\n", i, got, EXPECT[i]); bad++; }
        }
    }

    mole_rng_init(&r, 0);
    for (i = 0; i < 12000; i++) v = mole_rng_next_double(&r);
    { double want; sscanf(EXPECT_12000, "%lf", &want);
      if (want != v) { printf("  FAIL draw 12000: got %.17g want %s\n", v, EXPECT_12000); bad++; } }

    printf("mole_rng: %s (20 draws + draw 12000, bit-exact vs mono)\n",
           bad ? "FAILED" : "PASS");
    return bad ? 1 : 0;
}
