# End-to-end parity + timing proof for the hydro_project accelerator, run
# against the REAL vmdhole.tcl (never edited) and REAL trajectories.
#
# Usage:  vmd -dispdev text -e native/hydration/test_hydro_accel_parity.tcl
#
# What this does, per structure/settings combination:
#   1. Runs the real ::VMDHole::compute_hydration (100% original Tcl).
#   2. Runs ::VMDHole::_accel_compute_hydration (auto-generated by
#      gen_accel_compute_hydration.py: every line VERBATIM from vmdhole.tcl
#      except the water-COG/projection/binning sub-block, which calls
#      hydro_project instead -- see native/build.sh's hydro section).
#   3. Compares the two hydration_data dicts. hard-bin mode (water_kde=0) is
#      expected BYTE-IDENTICAL. KDE mode (the shipped default, water_kde=1)
#      is expected identical except for a documented, bounded, sub-1e-15
#      libm exp() cross-runtime rounding difference (see NOTES) that shows
#      up only in occ_std/energy_std/perframe_occ, never in the primary
#      occupancy/energy/density/countspf trajectory means in the cases
#      tested here.
#
# Structures used (both already have a completed HOLE run committed in this
# repo, so no HOLE re-run is needed just to prove hydration parity):
#   - case4 (step5_assembly.hmr/sim_1.dcd): CHARMM PSF/DCD, 50 frames,
#     manifest_full axis mode, 30600 waters.
#   - 4pirtm (scratch_chap_gromacs/chap-src/examples/example-02): GROMACS
#     .gro/.xtc, 11 frames, per-frame PCA axis mode (axis_drifts_per_frame=1
#     in its manifest) -- exercises a genuinely different code path/format/
#     water model than case4. Skipped gracefully if not present in this
#     checkout (it lives under a vendored GROMACS/CHAP source tree that may
#     not be checked out everywhere).
#
# This script does NOT edit vmdhole.tcl and does NOT require Tk (runs under
# -dispdev text). It regenerates accel_compute_hydration.tcl fresh each run
# via gen_accel_compute_hydration.py so it can never silently drift from the
# real proc.

# VMD's `-e` does not set [info script]/argv0 usefully, so locate ourselves
# via [pwd] instead: run this from the repo root
# (`vmd -dispdev text -e native/hydration/test_hydro_accel_parity.tcl`), from
# native/, or from native/hydration/ itself. HERE = native/ (where the built
# hydro_project binary lives); the source sits in native/hydration/.
if {[file exists [file join [pwd] native hydration hydro_project.c]]} {
    set HERE [file join [pwd] native]
} elseif {[file exists [file join [pwd] hydration hydro_project.c]]} {
    set HERE [pwd]
} elseif {[file exists [file join [pwd] hydro_project.c]]} {
    set HERE [file dirname [pwd]]
} else {
    puts stderr "FATAL: run this from the repo root, native/, or native/hydration/ (cwd=[pwd])"
    exit 2
}
set ROOT [file dirname $HERE]
set PLUGIN [file join $ROOT vmdhole vmdhole.tcl]

puts "Regenerating accel_compute_hydration.tcl from the current vmdhole.tcl..."
if {[catch {exec python3 [file join $HERE gen_accel_compute_hydration.py]} _gerr]} {
    puts stderr "FATAL: generator failed: $_gerr"
    exit 2
}
puts $_gerr

source $PLUGIN
proc tk_messageBox {args} { return yes }
proc ::VMDHole::activate_molecule {molid} { set ::VMDHole::active_molid $molid }
proc ::VMDHole::clear_surface {} { }
proc ::VMDHole::refresh_results_list {} { }
proc ::VMDHole::select_result {args} { }
proc ::VMDHole::apply_material_now {} { }
proc ::VMDHole::refresh_mean_surface_if_shown {} { }
proc ::VMDHole::draw_mean_profile {} { }
proc ::VMDHole::refresh_property_scheme_menus {} { }
proc ::VMDHole::on_hydro_method_changed {} { }

set ::HP_ACCEL_BIN [file join $HERE hydro_project]
if {![file exists $::HP_ACCEL_BIN]} {
    puts "Building hydro_project..."
    exec sh [file join $HERE build.sh]
}
source [file join $HERE accel_compute_hydration.tcl]

set ::HP_PASS 0
set ::HP_FAIL 0

proc hp_compare_and_report {label} {
    set orig_data $::VMDHole::hydration_data
    set ok 1
    return $orig_data
}

# Runs orig vs accel on the CURRENT molecule/result_frames/state, reports.
proc hp_run_case {label} {
    set t0 [clock microseconds]
    if {[catch {::VMDHole::compute_hydration} _e]} { puts "  ERROR (orig): $_e"; incr ::HP_FAIL; return }
    set t1 [clock microseconds]
    set orig_data $::VMDHole::hydration_data
    set orig_wall [expr {($t1-$t0)/1e6}]

    set ::HP_ACCEL_BATCH_DIR [file join $::HERE [format "accel_batch_%s" [string map {" " "_" "/" "_"} $label]]]
    file delete -force $::HP_ACCEL_BATCH_DIR
    set t2 [clock microseconds]
    if {[catch {::VMDHole::_accel_compute_hydration} _e]} { puts "  ERROR (accel): $_e"; incr ::HP_FAIL; return }
    set t3 [clock microseconds]
    set accel_data $::VMDHole::hydration_data
    set accel_wall [expr {($t3-$t2)/1e6}]
    file delete -force $::HP_ACCEL_BATCH_DIR

    puts "\n=== $label ==="
    puts [format "  orig_wall_s=%.4f  accel_wall_s=%.4f  speedup=%.2fx" \
        $orig_wall $accel_wall [expr {$accel_wall>0 ? $orig_wall/$accel_wall : 0}]]
    if {$orig_data eq $accel_data} {
        puts "  RESULT: BYTE-IDENTICAL"
        incr ::HP_PASS
        return
    }
    # Not byte-identical as a whole dict string - report per-key so a KDE-mode
    # last-ULP libm difference (expected, see NOTES) is distinguishable from a
    # real regression BY MAGNITUDE, not by which key it lands in: the exp()
    # ULP noise (~1e-16 per contributing term) can propagate into ANY Welford-
    # averaged key (occupancy/energy/density/countspf/occ_std/energy_std)
    # depending on which bins happen to straddle a rounding boundary for a
    # given selection/geometry - which key it hits is incidental, the bound
    # on HOW BIG the difference is is what actually distinguishes "expected
    # libm noise" from "a real bug". perframe_occ is a list-of-lists, so it
    # needs one extra level of recursion.
    set worst_maxabs 0.0
    proc _hp_scalar_diff {ov av} {
        upvar worst_maxabs worst_maxabs
        if {[llength $ov] != [llength $av]} { set worst_maxabs 1e300; return }
        foreach o $ov a $av {
            if {[string is double -strict $o] && [string is double -strict $a]} {
                if {$o != $a} {
                    set d [expr {abs($o-$a)}]
                    if {$d > $worst_maxabs} { set worst_maxabs $d }
                }
            } elseif {[string is list $o] && [llength $o] > 1} {
                _hp_scalar_diff $o $a
            } elseif {$o ne $a} {
                set worst_maxabs 1e300
            }
        }
    }
    foreach k [dict keys $orig_data] {
        set ov [dict get $orig_data $k]
        set av [expr {[dict exists $accel_data $k] ? [dict get $accel_data $k] : "<MISSING>"}]
        if {$ov eq $av} continue
        set before $worst_maxabs
        _hp_scalar_diff $ov $av
        puts [format "    key '%s' differs (this key's contribution to worst-so-far: %.3e)" $k $worst_maxabs]
    }
    # 1e-12 is a generous bound: observed noise on real data tops out around
    # 9e-16 (case4) - three orders of magnitude of headroom before this would
    # flag anything but the documented libm effect.
    if {$worst_maxabs < 1e-12} {
        puts [format "  RESULT: within the KDE exp() ULP tolerance noted above (worst diff %.3e)" $worst_maxabs]
        incr ::HP_PASS
    } else {
        puts [format "  RESULT: FAIL -- unexpected divergence (worst diff %.3e)" $worst_maxabs]
        incr ::HP_FAIL
    }
}

# --- case4: CHARMM PSF/DCD, manifest_full axis ---
set CASE4_PSF [file join $ROOT vmdhole step5_assembly.hmr.psf]
set CASE4_DCD [file join $ROOT vmdhole sim_1.dcd]
set CASE4_DIR [file join $ROOT vmdhole hole_output_step5_assembly.hmr]
if {[file exists $CASE4_PSF] && [file exists $CASE4_DCD] && [file isdirectory $CASE4_DIR]} {
    puts "\n########## case4 (CHARMM, 50 frames, manifest_full axis) ##########"
    set molid [mol new $CASE4_PSF]
    mol addfile $CASE4_DCD waitfor all
    ::VMDHole::init_executables
    set ::VMDHole::state(import_dir) $CASE4_DIR
    set ::VMDHole::state(import_molid) [molinfo top]
    ::VMDHole::import_results_from_folder
    set all_frames $::VMDHole::result_frames

    set ::VMDHole::result_frames [lrange $all_frames 0 49]
    set ::VMDHole::state(water_sel) "water and oxygen"
    set ::VMDHole::state(water_kde) 0
    set ::VMDHole::state(water_kde_bw) 1.4
    set ::VMDHole::state(water_dens_cap) 0.0
    set ::VMDHole::state(water_radius_floor) 0.0
    hp_run_case "case4/hardbin/N=50/water_and_oxygen"

    set ::VMDHole::result_frames [lrange $all_frames 0 49]
    set ::VMDHole::state(water_kde) 1
    hp_run_case "case4/kde_default/N=50/water_and_oxygen"

    set ::VMDHole::result_frames [lrange $all_frames 0 9]
    hp_run_case "case4/kde_default/N=10/water_and_oxygen"

    set ::VMDHole::result_frames [lrange $all_frames 0 49]
    set ::VMDHole::state(water_sel) "water"
    hp_run_case "case4/kde_default/N=50/whole_molecule_water"

    set ::VMDHole::state(water_sel) "water and oxygen"
    set ::VMDHole::state(water_dens_cap) 5.0
    set ::VMDHole::state(water_radius_floor) 1.4
    hp_run_case "case4/kde_default/N=50/dcap5_rfloor1.4"

    mol delete $molid
} else {
    puts "\nSKIPPED case4: fixtures not found under $ROOT/vmdhole (step5_assembly.hmr.psf / sim_1.dcd / hole_output_step5_assembly.hmr)"
}

# --- 4pirtm: GROMACS .gro/.xtc, per-frame PCA axis, different water model ---
set EX02 [file join $ROOT scratch_chap_gromacs chap-src examples example-02]
set PIRTM_GRO [file join $EX02 4pirtm.gro]
set PIRTM_XTC [file join $EX02 4pirtm.xtc]
set PIRTM_DIR [file join $EX02 hole_output_4pirtm]
if {[file exists $PIRTM_GRO] && [file exists $PIRTM_XTC] && [file isdirectory $PIRTM_DIR]} {
    puts "\n########## 4pirtm (GROMACS, 11 frames, per-frame PCA axis) ##########"
    set molid2 [mol new $PIRTM_GRO]
    mol addfile $PIRTM_XTC waitfor all
    set ::VMDHole::state(import_dir) $PIRTM_DIR
    set ::VMDHole::state(import_molid) [molinfo top]
    ::VMDHole::import_results_from_folder

    set ::VMDHole::state(water_sel) "water and oxygen"
    set ::VMDHole::state(water_kde) 0
    set ::VMDHole::state(water_kde_bw) 1.4
    set ::VMDHole::state(water_dens_cap) 0.0
    set ::VMDHole::state(water_radius_floor) 0.0
    hp_run_case "4pirtm/hardbin/water_and_oxygen"

    set ::VMDHole::state(water_kde) 1
    hp_run_case "4pirtm/kde_default/water_and_oxygen"

    mol delete $molid2
} else {
    puts "\nSKIPPED 4pirtm: fixtures not found under $EX02"
}

puts "\n\n==================== SUMMARY ===================="
puts "PASS: $::HP_PASS   FAIL: $::HP_FAIL"
if {$::HP_FAIL > 0} { exit 1 }
exit 0
