#!/bin/sh
# The pure-Tcl MOLE engine must reproduce the C engine EXACTLY.
#
# The standing rule is that Tcl works standalone and C is acceleration only, so
# the two must agree - and for this engine "agree" means the identical mesh in
# the identical slots, not merely a valid Delaunay triangulation of the same
# points. Tetrahedron indices are load-bearing downstream: component iteration
# is index-ordered, and a MaxClearance tie is settled by lowest index. A mesh
# differing only in slot layout would pass a set comparison and produce
# different tunnels.
#
# The defect class this exists for is the one that has cost the most time in
# this port: a stage that is "obviously" a transcription, is not, and whose
# error only shows up several stages later as a plausible-looking wrong tunnel.
# It also stops the two cross-checks rotting - they were written as one-off
# manual runs, reachable from no script, which is how a green suite ends up
# proving nothing.
#
# Reference data is generated by the C itself at run time rather than committed,
# so the test compares the two implementations as they are now, not the Tcl
# against a snapshot of a C that has since changed.
DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
SRC="$DIR/../../native"
FIX="$DIR/fixtures/mole_atoms_1tqn.txt"
echo "=============================================================="
echo "mole-tcl-port: $DIR/../mole_delaunay.tcl vs $SRC/voronoi/vor_delaunay.c"
pass=0; fail=0
ok()  { echo "  PASS  $1"; pass=$((pass+1)); }
bad() { echo "  FAIL  $1"; fail=$((fail+1)); }

CC=${CC:-cc}
command -v "$CC"    >/dev/null 2>&1 || { echo "SKIP: no C compiler"; exit 0; }
command -v tclsh    >/dev/null 2>&1 || { echo "SKIP: no tclsh"; exit 0; }
[ -f "$FIX" ] || { echo "  FAIL  fixture missing: $FIX"; exit 1; }

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

# MOLE mode's grid, not the default: MOLE's +-0.00005 A jitter is rounded away
# entirely at VP_SCALE 1000, which is why the engine is a separate binary.
MOLE_FLAGS="-DVP_SCALE=100000.0 -DVP_MAX_COORD=20000000L"

if ! "$CC" -O2 $MOLE_FLAGS -o "$TMP/cases" "$SRC/mole/mole_predicate_cases.c" \
        "$SRC/voronoi/vor_predicates.c" -lm 2>"$TMP/err"; then
    bad "mole_predicate_cases did not build"; sed 's/^/       /' "$TMP/err"
fi
if ! "$CC" -O2 $MOLE_FLAGS -o "$TMP/dump" "$SRC/mole/mole_dt_dump.c" \
        "$SRC/mole/mole_complex.c" "$SRC/mole/mole_rng.c" "$SRC/voronoi/vor_delaunay.c" \
        "$SRC/voronoi/vor_predicates.c" -lm 2>"$TMP/err"; then
    bad "mole_dt_dump did not build"; sed 's/^/       /' "$TMP/err"
fi
if ! "$CC" -O2 $MOLE_FLAGS -o "$TMP/cxdump" "$SRC/mole/mole_complex_dump.c" \
        "$SRC/mole/mole_complex.c" "$SRC/mole/mole_rng.c" "$SRC/voronoi/vor_delaunay.c" \
        "$SRC/voronoi/vor_predicates.c" -lm 2>"$TMP/err"; then
    bad "mole_complex_dump did not build"; sed 's/^/       /' "$TMP/err"
fi
if ! "$CC" -O2 $MOLE_FLAGS -o "$TMP/tndump" "$SRC/mole/mole_tunnel_dump.c" \
        "$SRC/mole/mole_tunnel.c" "$SRC/mole/mole_complex.c" "$SRC/mole/mole_rng.c" \
        "$SRC/voronoi/vor_delaunay.c" "$SRC/voronoi/vor_predicates.c" -lm 2>"$TMP/err"; then
    bad "mole_tunnel_dump did not build"; sed 's/^/       /' "$TMP/err"
fi

# The PRODUCTION engine, built from current source. Previously the end-to-end
# checks below invoked the pre-existing $SRC/mole/mole_tunnel_engine binary, so a
# regression in mole_main.c stayed green against yesterday's build. Build it
# here and point the rest of the script at this one; fall back to the tracked
# binary only if the build fails, and say so rather than passing silently.
# mole_auto_origins writes into the caller's fixed MOLE_MAX_ORIGINS array. The
# canary test below fails against the pre-fix routine on any fixture (its
# max_origins==0 case wrote an element unconditionally), so it does not need a
# structure with 17+ qualifying maxima to be meaningful.
if "$CC" -O2 $MOLE_FLAGS -I"$SRC" -o "$TMP/maxorig" "$SRC/mole/mole_maxorigins_test.c" \
        "$SRC/mole/mole_tunnel.c" "$SRC/mole/mole_lining.c" "$SRC/mole/mole_complex.c" \
        "$SRC/mole/mole_dh.c" "$SRC/mole/mole_rng.c" "$SRC/voronoi/vor_delaunay.c" \
        "$SRC/voronoi/vor_predicates.c" -lm 2>"$TMP/err"; then
    if "$TMP/maxorig" "$DIR/fixtures/mole_atoms_1tqn.txt" > "$TMP/mo" 2>&1; then
        ok "mole_auto_origins never writes past its caller's origins array"
    else
        bad "mole_auto_origins overflowed its caller's array"
        sed 's/^/       /' "$TMP/mo"
    fi
else
    bad "mole_maxorigins_test did not build"; sed 's/^/       /' "$TMP/err"
fi

MOLE_ENGINE="$TMP/mole_tunnel_engine"
if ! "$CC" -O2 $MOLE_FLAGS -o "$MOLE_ENGINE" "$SRC/mole/mole_main.c" \
        "$SRC/mole/mole_tunnel.c" "$SRC/mole/mole_lining.c" "$SRC/mole/mole_complex.c" \
        "$SRC/mole/mole_dh.c" "$SRC/mole/mole_rng.c" "$SRC/voronoi/vor_delaunay.c" \
        "$SRC/voronoi/vor_predicates.c" -lm 2>"$TMP/err"; then
    bad "mole_tunnel_engine did not build from current source"
    sed 's/^/       /' "$TMP/err"
    MOLE_ENGINE="$SRC/mole/mole_tunnel_engine"
fi

# ---- 1. exact predicates: the two decisions the triangulation is built from --
if [ -x "$TMP/cases" ]; then
    "$TMP/cases" > "$TMP/cases.txt"
    if tclsh "$DIR/test_mole_predicates.tcl" "$TMP/cases.txt" > "$TMP/out" 2>&1; then
        ok "exact predicates match the C"
    else
        bad "exact predicates differ from the C"
    fi
    sed 's/^/     /' "$TMP/out"
fi

# ---- 2. the triangulation itself, slot for slot ----------------------------
# 200 points, not a whole protein: the point is parity, and the Tcl build is
# ~1.3 ms per point, so a full structure would put 5 s into every suite run.
# Parity at 200 and at 3809 was established the same way.
if [ -x "$TMP/dump" ]; then
    "$TMP/dump" "$FIX" "$TMP/pts.txt" "$TMP/tet.txt" 200 > "$TMP/dumpout" 2>&1 \
        || bad "mole_dt_dump failed: $(cat "$TMP/dumpout")"
    if [ -f "$TMP/tet.txt" ]; then
        if tclsh "$DIR/test_mole_delaunay.tcl" "$TMP/pts.txt" "$TMP/tet.txt" "$FIX" \
                > "$TMP/out" 2>&1; then
            ok "Tcl Delaunay reproduces the C mesh slot for slot"
        else
            bad "Tcl Delaunay differs from the C mesh"
        fi
        sed 's/^/     /' "$TMP/out"
    fi
fi

# ---- 3. the cavity pipeline, quantity by quantity ---------------------------
# Run twice on purpose. 200 pivots is the fast case; 1200 is the smallest slice
# of 1tqn that yields a CHANNEL, so the channel/void classification and the
# depth filters are exercised rather than merely present. Cavity counts alone
# are a weak check - they survived several of the arithmetic-form errors this
# port already hit - so the test compares every per-tetrahedron and per-edge
# double exactly.
if [ -x "$TMP/cxdump" ]; then
    for n in 200 1200; do
        "$TMP/cxdump" "$FIX" "$TMP/cx$n.txt" "$n" > "$TMP/cxout" 2>&1 \
            || bad "mole_complex_dump $n failed: $(cat "$TMP/cxout")"
        [ -f "$TMP/cx$n.txt" ] || continue
        if tclsh "$DIR/test_mole_complex.tcl" "$FIX" "$TMP/cx$n.txt" "$n" \
                > "$TMP/out" 2>&1; then
            ok "Tcl cavity pipeline matches the C at $n pivots ($(sed -n 's/.*components = \([0-9]*\), channels = \([0-9]*\).*/\1 components, \2 channels/p' "$TMP/out" | head -1))"
        else
            bad "Tcl cavity pipeline differs from the C at $n pivots"
        fi
        sed 's/^/     /' "$TMP/out"
    done
    # Same comparison on the mixed-case fixture, which is the only one where the
    # two chain-collation rules disagree. The slice is taken AFTER ordering, so
    # an ordinal Tcl comparator would put a different chain's atoms in it and
    # every quantity downstream would move.
    ERIMC0="$DIR/fixtures/mole_atoms_1eri_mixedcase.txt"
    if [ -f "$ERIMC0" ]; then
        "$TMP/cxdump" "$ERIMC0" "$TMP/cxmc.txt" 1200 > "$TMP/cxout" 2>&1 \
            || bad "mole_complex_dump on the mixed-case fixture failed"
        if [ -f "$TMP/cxmc.txt" ]; then
            if tclsh "$DIR/test_mole_complex.tcl" "$ERIMC0" "$TMP/cxmc.txt" 1200 \
                    > "$TMP/out" 2>&1; then
                ok "Tcl chain collation matches the C on mixed-case chains"
            else
                bad "Tcl chain collation differs from the C - see _chain_cmp"
            fi
            sed 's/^/     /' "$TMP/out"
        fi
    fi
fi

# ---- 4. the tunnel stage, intermediate by intermediate ----------------------
# 2400 pivots is the smallest slice of 1tqn on which two tunnels from the SAME
# origin reach the similarity filter at all - below that it never runs.
#
# MaxTunnelSimilarity is set to 0.5, the other end of MOLE's own clamp range,
# and that is not an arbitrary choice: at the 0.9 default the filter never
# REMOVES anything, on 1tqn at any size or on 1BL8, so its verdict is "keep"
# everywhere and the asymmetric 6-vs-2 sampling and the sort-then-sweep removal
# order are never tested. Verified: sampling both tunnels at 6 per Angstrom -
# the natural way to write it, and wrong - is invisible at 0.9 and caught at 0.5.
#
# Run twice. The second pass carries a NONZERO BottleneckTolerance, which no
# other check here does: at tolerance 0 the filter's whole tolerance branch
# (mole_tunnel.c:840-856, mole_tunnel.tcl:757-773) is dead in both engines, so
# a parity run at the default proves nothing about it.
if [ -x "$TMP/tndump" ]; then
    for v in "0.0 default tolerance" "3.0 tolerance 3.0"; do
        set -- $v
        btol=$1; shift
        "$TMP/tndump" "$FIX" "$TMP/tn.txt" 2400 0.5 1.6 "$btol" > "$TMP/tnout" 2>&1 \
            || bad "mole_tunnel_dump failed: $(cat "$TMP/tnout")"
        if [ -f "$TMP/tn.txt" ]; then
            if tclsh "$DIR/test_mole_tunnel.tcl" "$FIX" "$TMP/tn.txt" 2400 0.5 \
                    1.6 "$btol" > "$TMP/out" 2>&1; then
                ok "Tcl tunnel stage matches the C at 2400 pivots ($*)"
            else
                bad "Tcl tunnel stage differs from the C at 2400 pivots ($*)"
            fi
            sed 's/^/     /' "$TMP/out"
        fi
    done
fi

# ---- 5. against MOLE ITSELF, which nothing else here does -------------------
# Every other check compares us against us. This one uses MOLE 2's own CSV
# export for its shipped 1tqn test, produced by MOLE, and is the only thing that
# pins FreeRadius and BRadius to the reference implementation rather than to the
# own reading of it. The origin is test.xml's: the centroid of residues A308 and
# A309, which MOLE snaps to Cavity 1.
REF="$DIR/fixtures/mole_reference/test_xml"
REFHEM="$DIR/fixtures/mole_reference/hem_origin"
if [ -x "$MOLE_ENGINE" ] && [ -f "$REF/tunnel_1.csv" ]; then
    ORI=$(awk '$6=="A" && ($7==308 || $7==309) {x+=$1;y+=$2;z+=$3;n++} \
               END{printf "%.6f %.6f %.6f", x/n, y/n, z/n}' "$FIX")
    if "$MOLE_ENGINE" "$FIX" "$TMP/gt.txt" 3.0 1.25 8 5.0 0.0 0 \
            $ORI 5.0 > "$TMP/gtout" 2>&1; then
        if python3 "$DIR/mole_ground_truth.py" "$TMP/gt.txt" "$REF" > "$TMP/out" 2>&1; then
            ok "profiles match MOLE 2's own export (Radius, FreeRadius, BRadius, XYZ)"
        else
            bad "profiles differ from MOLE 2's own export"
        fi
        sed 's/^/     /' "$TMP/out"
        # Cavities: their property block uses a DIFFERENT rule from the layers'
        # one (every residue also contributes the backbone constants), so a port
        # that reuses the layer rule matches every tunnel and every cavity is
        # still wrong.
        if [ -f "$REF/cavities.xml" ]; then
            if python3 "$DIR/mole_cavity_truth.py" "$TMP/gt.txt" "$REF/cavities.xml" \
                    > "$TMP/out" 2>&1; then
                ok "cavities match MOLE's own export (residues + properties)"
            else
                bad "cavities differ from MOLE's own export"
            fi
            sed 's/^/     /' "$TMP/out"
        fi
        # The layers discriminate where the profiles cannot: tunnels.csv gives
        # ten aggregates per tunnel, and a misclassified backbone atom or a
        # shifted merge boundary can cancel out inside a length-weighted mean.
        if python3 "$DIR/mole_lining_truth.py" "$TMP/gt.txt" "$REF" > "$TMP/out" 2>&1; then
            ok "lining layers match MOLE 2's own XML (residues, widths, properties)"
        else
            bad "lining layers differ from MOLE 2's own XML"
        fi
        sed 's/^/     /' "$TMP/out"
        # The plugin's READER, against the same reference: a field taken from
        # the wrong column is invisible to a byte-comparison of the file and
        # fatal to whatever displays it.
        if tclsh "$DIR/test_mole_lining_parse.tcl" "$TMP/gt.txt" "$REF/tunnels.csv" \
                > "$TMP/out" 2>&1; then
            ok "the plugin's reader recovers the lining from the engine's file"
        else
            bad "the plugin's lining reader disagrees with MOLE's own numbers"
        fi
        sed 's/^/     /' "$TMP/out"
    else
        bad "engine failed on the ground-truth run: $(tail -2 "$TMP/gtout")"
    fi
else
    echo "  SKIP  ground truth needs the engine binary and MOLE's reference CSVs"
fi

# ---- 6. the ENGINE OUTPUT FILE, byte for byte -------------------------------
# Everything above compares values; the plugin reads a FILE. A formatting
# difference - a %.4f against a %.3f, a different sample count - is invisible to
# a trace comparison and fatal to the parser, so until the two files match the
# Tcl path is not a drop-in fallback for the engine.
#
# The atom table is regenerated at %.3f WITH the B-factor and atom-name columns,
# exactly the way _tunnel_atoms_mole writes one, so this exercises the plugin's
# real coordinate interface and puts the L/F/Y/W lining block inside the
# byte-for-byte comparison rather than only the T/P profile.
if [ -x "$MOLE_ENGINE" ]; then
    awk 'NR<=2400 {printf "%.3f %.3f %.3f %s %d %s %s %s %.2f %s\n",
                   $1,$2,$3,$4,$5,$6,$7,$8,$9,$10}' \
        "$FIX" > "$TMP/plugin_atoms.txt"
    if "$MOLE_ENGINE" "$TMP/plugin_atoms.txt" "$TMP/c_engine.txt" \
            > "$TMP/engout" 2>&1; then
        if tclsh "$DIR/test_mole_engine_file.tcl" "$TMP/plugin_atoms.txt" \
                "$TMP/c_engine.txt" "$TMP/tcl_engine.txt" > "$TMP/out" 2>&1; then
            ok "Tcl writes the engine's output file byte for byte"
        else
            bad "Tcl engine output file differs from the C's"
        fi
        sed 's/^/     /' "$TMP/out"
    else
        echo "  SKIP  mole_tunnel_engine did not run: $(cat "$TMP/engout")"
    fi
else
    echo "  SKIP  mole_tunnel_engine not built - run native/build.sh"
fi

# ---- 7. the PLUGIN's own call, with the binary and without it ---------------
# The glue nothing else covers: the dispatch in _tunnel_search_mole, the
# on-demand load of the Tcl modules from plugin_dir, and _tunnel_atoms_mole
# feeding both paths. Everything above starts from a fixture file; here the
# coordinates come from VMD and the caller is the plugin.
# 9HNR is deliberately not tracked (large het structure); place a copy at
# tests/fixtures/9HNR.pdb to exercise this arm - it skips cleanly otherwise.
PDB="$DIR/fixtures/9HNR.pdb"
if [ -f "$PDB" ] && [ -x "$MOLE_ENGINE" ] && command -v "${VMD:-vmd}" >/dev/null 2>&1; then
    # Under a timeout: if the dispatcher stops routing to MOLE it falls through
    # to the lattice search's pure-Tcl path, which does not finish on this
    # structure. A hanging test is worse than a failing one.
    TMO=""; command -v timeout >/dev/null 2>&1 && TMO="timeout 180"
    VH="$DIR/.." PDB="$PDB" SOS="$SRC/sos_triangle_fast" OUT="$TMP/fb.txt" \
    SEL="protein and chain A and resid 1 to 200" \
        $TMO "${VMD:-vmd}" -dispdev text -e "$DIR/mole_fallback_check.tcl" > "$TMP/fbout" 2>&1
    if [ -f "$TMP/fb.txt" ]; then
        ntun=$(awk '$1=="tunnels"{print $2}' "$TMP/fb.txt")
        same=$(awk '$1=="identical"{print $2}' "$TMP/fb.txt")
        cst=$(awk '$1=="c_status"{print $2}' "$TMP/fb.txt")
        tst=$(awk '$1=="tcl_status"{print $2}' "$TMP/fb.txt")
        # ntun > 0 matters: an empty payload would match trivially.
        deng=$(awk '$1=="dispatch_engine"{print $2}' "$TMP/fb.txt")
        dtun=$(awk '$1=="dispatch_tunnels"{print $2}' "$TMP/fb.txt")
        case "$deng" in
            mole-*) ok "tunnel_search dispatches to $deng ($dtun tunnels)" ;;
            *)      bad "tunnel_search dispatched to '$deng', not MOLE - the selector says mole" ;;
        esac
        cp=$(awk '$1=="cfg_probe"{print $2}' "$TMP/fb.txt")
        cw=$(awk '$1=="cfg_weight"{print $2}' "$TMP/fb.txt")
        cwb=$(awk '$1=="cfg_weight_bogus"{print $2}' "$TMP/fb.txt")
        if [ "$cp" = 4.0 ] && [ "$cw" = 1 ] && [ "$cwb" = 0 ]; then
            ok "panel parameters reach the engine (probe $cp, weight $cw, bogus -> $cwb)"
        else
            bad "panel parameters not plumbed through (probe=$cp weight=$cw bogus=$cwb)"
        fi
        if [ "$same" = 1 ] && [ "$cst" = ok ] && [ "$tst" = ok ] && [ "${ntun:-0}" -gt 0 ]; then
            ok "both paths agree at NON-DEFAULT parameters ($ntun tunnels)"
        else
            bad "plugin fallback differs (c=$cst tcl=$tst tunnels=$ntun identical=$same)"
            sed 's/^/       /' "$TMP/fb.txt"
        fi
        # The Lining window reads tunnel_lining($frame); nothing else fills it,
        # so if the search does not store it the panel is permanently empty and
        # no other check would notice.
        ps=$(awk '$1=="prop_spheres"{print $2}' "$TMP/fb.txt")
        pd=$(awk '$1=="prop_distinct"{print $2}' "$TMP/fb.txt")
        pr=$(awk '$1=="prop_range"{print $2}' "$TMP/fb.txt")
        # >1 distinct value is the point: a coloring that is constant along the
        # tunnel renders as one flat color and looks exactly like "off".
        if [ "${ps:-0}" -gt 0 ] && [ "${pd:-0}" -gt 1 ] && [ "${pr:-0}" = 1 ]; then
            ok "property coloring varies along the tunnel ($ps points, $pd values)"
        else
            bad "property coloring degenerate (points=$ps distinct=$pd range_ok=$pr)"
        fi
        lt=$(awk '$1=="lining_tunnels"{print $2}' "$TMP/fb.txt")
        ll=$(awk '$1=="lining_layers"{print $2}' "$TMP/fb.txt")
        if [ "${lt:-0}" -gt 0 ] && [ "${ll:-0}" -gt 0 ] && [ "${lt:-0}" = "${ntun:-x}" ]; then
            ok "the search stores the lining for the panel ($lt tunnels, $ll layers)"
        else
            bad "tunnel_lining not populated (tunnels=$lt layers=$ll, expected $ntun)"
        fi
        sed -n 's/^timing \(.*\) \(.*\)$/       binary \1 ms, pure Tcl \2 ms/p' "$TMP/fb.txt"
        sed -n 's/^tcl_diag /       /p' "$TMP/fb.txt"
    else
        bad "plugin fallback check did not run"; tail -5 "$TMP/fbout" | sed 's/^/       /'
    fi
else
    echo "  SKIP  plugin fallback check needs VMD, the engine binary and 9HNR.pdb"
fi

# ---- 8. the same check under VMD's OWN Tcl, which is the one that ships -----
# Not redundant with 2: this path exists so Tcl works standalone INSIDE VMD, and
# this project has twice been bitten by the dev interpreter and the deployed one
# behaving differently. VMD carries its own Tcl 8.5 and its own tcl_precision,
# which decides whether a double survives the round-trip in the jitter.
VMD=${VMD:-vmd}
if [ -f "$TMP/tet.txt" ] && command -v "$VMD" >/dev/null 2>&1; then
    cat > "$TMP/under_vmd.tcl" <<'EOF'
set argv [list $::env(MDT_PTS) $::env(MDT_TET) $::env(MDT_ATOMS)]
set argc 3
set ::mdt_rc [catch {source $::env(MDT_TEST)} ::mdt_err]
EOF
    MDT_PTS="$TMP/pts.txt" MDT_TET="$TMP/tet.txt" MDT_ATOMS="$FIX" \
    MDT_TEST="$DIR/test_mole_delaunay.tcl" \
        "$VMD" -dispdev text -e "$TMP/under_vmd.tcl" > "$TMP/vmdout" 2>&1
    # The test's own exit code is swallowed by VMD, so assert on its report: every
    # line it prints ends PASS or FAIL, and the build line must be there at all.
    if grep -q "every slot identical" "$TMP/vmdout" && ! grep -q "FAIL" "$TMP/vmdout"; then
        ok "same parity under VMD's own Tcl"
    else
        bad "parity differs under VMD's Tcl"
        grep -E "PASS|FAIL|Error" "$TMP/vmdout" | sed 's/^/       /'
    fi
    grep -E "PASS|FAIL" "$TMP/vmdout" | sed 's/^/     /'
else
    echo "  SKIP  VMD not on PATH - system tclsh only"
fi

# NOTE: the exit status is asserted at the END of this file, not here. A bare
# `[ "$fail" -eq 0 ]` in the middle only sets $? for the next command; sections 7+
# run afterwards and the script's last command was an echo, so a regression in
# any later section still exited 0 and CI would have reported green.

# ---- 7. MOLE's name sets, C against Tcl -------------------------------------
# The only part of the port no ground-truth run touches: every reference
# structure is protein, no hydrogens, no nucleic acid, so backboneNames' H entry
# and its whole nucleic half are never compared against MOLE. Both engines keep
# their own copy of the set, and copies drift.
if "$CC" -O2 -I "$SRC" -o "$TMP/classify" "$SRC/mole/mole_classify_dump.c" \
        "$SRC/mole/mole_complex.c" "$SRC/mole/mole_rng.c" "$SRC/voronoi/vor_delaunay.c" \
        "$SRC/voronoi/vor_predicates.c" -lm 2>"$TMP/cerr"; then
    "$TMP/classify" > "$TMP/classify_c.txt"
    if tclsh "$DIR/test_mole_classify.tcl" "$TMP/classify_c.txt" > "$TMP/out" 2>&1; then
        ok "MOLE's backbone/amino name sets agree in both engines"
    else
        bad "backbone/amino name sets differ between C and Tcl"
    fi
    sed 's/^/     /' "$TMP/out"
else
    echo "  SKIP  classify dump did not build: $(tail -1 "$TMP/cerr")"
fi

# ---- 8. heteroatoms in the lining ------------------------------------------
# MOLE's shipped PDBs are stripped of HETATM, and at test.xml's origin 1tqn's
# three tunnels never touch its heme - excluding HEM from the free set leaves
# all 631 profile rows unchanged. So the "not a standard residue" half of
# IsHetAtom, and the GetResidueProperties -> null path it leads to, has no
# ground-truth coverage. Putting the origin ON the heme iron forces HEM into the
# lining; the check then re-derives every property from the table independently.
if [ -x "$MOLE_ENGINE" ]; then
    FE=$(awk '$8=="HEM" && $10=="FE" {print $1, $2, $3; exit}' "$FIX")
    if [ -n "$FE" ]; then
        "$MOLE_ENGINE" "$FIX" "$TMP/het.txt" 3.0 1.25 8 5.0 0.0 0 \
            $FE 12.0 > "$TMP/hetout" 2>&1
        if python3 "$DIR/mole_het_check.py" "$TMP/het.txt" > "$TMP/out" 2>&1; then
            ok "heteroatoms line the tunnel and contribute no properties"
        else
            bad "heteroatom lining or property arithmetic is wrong"
        fi
        sed 's/^/     /' "$TMP/out"
        # Same run against MOLE's own output for it. This origin snaps into TWO
        # cavities, so it is also the only check that pins the tunnel ORDER:
        # MOLE sorts on (Cavity.Id, Length), and a plain length sort agrees with
        # that on every single-cavity run.
        if [ -f "$REFHEM/tunnels.xml" ]; then
            if python3 "$DIR/mole_lining_truth.py" "$TMP/het.txt" "$REFHEM" \
                    > "$TMP/out" 2>&1; then
                ok "heme-origin run matches MOLE, ids and all (2 cavities)"
            else
                bad "heme-origin run differs from MOLE"
            fi
            sed 's/^/     /' "$TMP/out"
        else
            echo "  SKIP  no MOLE reference for the heme origin ($REFHEM)"
        fi
    else
        echo "  SKIP  fixture has no HEM FE to aim at"
    fi
fi

# ---- 9. nucleic acid: the other half of backboneNames -----------------------
# Every protein reference leaves 11 of MOLE's 19 backbone names dead code -
# P, OP1/OP2, O1P/O2P and the six sugar carbons/oxygens. 1ERI (EcoRI bound to
# its DNA) exercises them: DNA lines its tunnels, and it lines them BOTH at the
# phosphate backbone and at the bases, so the per-layer backbone split turns on
# names no other structure has.
#
# It is also the only reference where MOLE's cavity ids are NOT the order the
# pipeline produces components in - its four tunnels are C1 8.99, C2 7.74,
# C3 11.94, C4 9.92 - so it is what pins Cavity.Id to a descending-VOLUME rank.
ERI="$DIR/fixtures/mole_atoms_1eri.txt"
REFERI="$DIR/fixtures/mole_reference/1ERI"
if [ -x "$MOLE_ENGINE" ] && [ -f "$ERI" ] && [ -f "$REFERI/tunnels.xml" ]; then
    if "$MOLE_ENGINE" "$ERI" "$TMP/eri.txt" > "$TMP/eriout" 2>&1; then
        if python3 "$DIR/mole_lining_truth.py" "$TMP/eri.txt" "$REFERI" \
                > "$TMP/out" 2>&1; then
            ok "protein-DNA complex matches MOLE (nucleic backbone names)"
        else
            bad "protein-DNA lining differs from MOLE"
        fi
        sed 's/^/     /' "$TMP/out"
        n=$(grep -oE "D[ACGT]:[0-9]+:[A-Z]:[01]" "$TMP/eri.txt" | sort -u | wc -l)
        if [ "$n" -gt 0 ]; then
            ok "DNA residues reach the lining ($n distinct residue/backbone pairs)"
        else
            bad "no DNA in the lining - this run does not exercise the nucleic path"
        fi
    else
        bad "engine failed on 1ERI: $(tail -2 "$TMP/eriout")"
    fi
else
    echo "  SKIP  1ERI fixture or MOLE reference missing"
fi

# ---- 8b. very-short profiles: MOLE's own derived verdict, and its margin ----
# GetProfile divides by numPoints-1, so a tunnel shorter than 1/density gives
# MOLE dt = +Inf and a NaN curve parameter. FilterBottleneck's own comparisons
# on that profile are all "NaN < x" - false unconditionally under IEEE - so
# MOLE keeps a fully-degenerate tunnel EVERY time, in both the tolerance==0 and
# tolerance!=0 branches. That is not a skipped case, it is a derived verdict,
# and both engines now match it directly (mole_filter_bottleneck_test.c,
# mole_filter_bottleneck_test.tcl) rather than attempting the NaN arithmetic
# itself - Tcl cannot: Inf*0 raises a domain error where IEEE yields NaN.
#
# The old clamp (n=1, then evaluate two real points) was WRONG: it rejected 4
# of 8 constructed degenerate cases that MOLE would keep. Both direct tests are
# verified to fail on that old clamp.
if [ -x "$TMP/fbtest" ] || "$CC" -O2 -I "$SRC" -o "$TMP/fbtest" \
        "$SRC/mole/mole_filter_bottleneck_test.c" "$SRC/mole/mole_tunnel.c" \
        "$SRC/mole/mole_complex.c" "$SRC/mole/mole_rng.c" "$SRC/voronoi/vor_delaunay.c" \
        "$SRC/voronoi/vor_predicates.c" -lm 2>"$TMP/fberr"; then
    if "$TMP/fbtest" > "$TMP/out" 2>&1; then ok "C keeps every degenerate profile, matching MOLE"
    else bad "C rejected a degenerate profile MOLE would keep"; fi
    sed 's/^/   /' "$TMP/out"
else
    bad "mole_filter_bottleneck_test did not build: $(tail -1 "$TMP/fberr")"
fi
if tclsh "$DIR/mole_filter_bottleneck_test.tcl" > "$TMP/out" 2>&1; then
    ok "Tcl keeps every degenerate profile, matching MOLE"
else
    bad "Tcl rejected a degenerate profile MOLE would keep"
fi
sed 's/^/   /' "$TMP/out"

# Not observed in the tested structures - not proven unreachable, since the
# control path's minimum tetrahedron count is no length floor. Kept as a live
# measurement rather than dropped now that the branch is correct, since the
# margin is what says a real structure would be safe even before reaching the
# derived-verdict code path: the shortest CANDIDATE profile, before any
# filter, against the loosest gate that consumes one (GetProfile(2), 0.5 A).
if [ -x "$TMP/tndump" ]; then
    worst=""
    for f in "$DIR"/fixtures/mole_atoms_*.txt; do
        "$TMP/tndump" "$f" "$TMP/len.txt" 99999 0.9 >/dev/null 2>&1 || continue
        m=$(awk '$1=="R"{print $5}' "$TMP/len.txt" | sort -g | head -1)
        [ -n "$m" ] || continue
        if [ -z "$worst" ] || awk "BEGIN{exit !($m < $worst)}"; then worst=$m; fi
    done
    if [ -n "$worst" ] && awk "BEGIN{exit !($worst > 0.5)}"; then
        ok "shortest candidate profile $(printf %.2f "$worst") A stays above the 0.5 A gate"
    else
        bad "a candidate profile reached the degenerate gate ($worst A) - the
             clamp in mole_filter_bottleneck is now a real divergence from MOLE"
    fi
fi

# ---- 9a. the chain comparator itself, against MOLE's own printed order -------
# The fixture checks below exercise the comparator through a whole pipeline.
# This pins the RULE, so a reviewer can see what it is without running MOLE.
if "$CC" -O2 $MOLE_FLAGS -I "$SRC" -o "$TMP/cct" "$SRC/mole/mole_chain_cmp_test.c" \
        "$SRC/mole/mole_complex.c" "$SRC/mole/mole_rng.c" "$SRC/voronoi/vor_delaunay.c" \
        "$SRC/voronoi/vor_predicates.c" -lm 2>"$TMP/ccterr"; then
    if "$TMP/cct" > "$TMP/out" 2>&1; then ok "C chain collation matches MOLE"
    else bad "C chain collation differs from MOLE"; fi
    sed 's/^/   /' "$TMP/out"
else
    bad "mole_chain_cmp_test did not build: $(tail -1 "$TMP/ccterr")"
fi
if tclsh "$DIR/chain_collation.tcl" > "$TMP/out" 2>&1; then
    ok "Tcl chain collation matches MOLE"
else
    bad "Tcl chain collation differs from MOLE"
fi
sed 's/^/   /' "$TMP/out"

# ---- 9a2. ResidueFlow and HetResidues, with a fixture that DISTINGUISHES -----
# The mixed-case fixture below (9b) passes ResidueFlow/HetResidues under
# EITHER chain rule, because ComputeFlow dedups first-seen across layers - so
# those two fixes rested on reading the source, not on a case that could
# fail. This check closes that gap. MOLE's own first-seen search has no
# chain restriction, so
# oligomeric pores commonly get multi-chain FIRST layers: 1BL8's own reference
# already has one (THR 107 A,C,D). Relabelled a/C/D, this is exactly that case.
# HetResidues needs no such construction - Distinct's order never survives
# into it, so a 2-residue synthetic table (DA 6 b, DA 7 B) is enough.
# mole_build_flow and mole_sort_residues_by_chain are exposed (were
# static/inline) so both are driven directly rather than through full protein
# geometry. Both assertions verified to fail against the ordinal comparator.
if "$CC" -O2 -I "$SRC" -o "$TMP/lrtest" "$SRC/mole/mole_lining_regression_test.c" \
        "$SRC/mole/mole_lining.c" "$SRC/mole/mole_tunnel.c" "$SRC/mole/mole_complex.c" \
        "$SRC/mole/mole_rng.c" "$SRC/voronoi/vor_delaunay.c" "$SRC/voronoi/vor_predicates.c" \
        -lm 2>"$TMP/lrerr"; then
    if "$TMP/lrtest" > "$TMP/out" 2>&1; then
        ok "C: ResidueFlow and HetResidues collate on a distinguishing fixture"
    else
        bad "C: ResidueFlow or HetResidues differ from MOLE's derived order"
    fi
    sed 's/^/   /' "$TMP/out"
else
    bad "mole_lining_regression_test did not build: $(tail -1 "$TMP/lrerr")"
fi
if tclsh "$DIR/mole_lining_regression_test.tcl" > "$TMP/out" 2>&1; then
    ok "Tcl: ResidueFlow and HetResidues collate on a distinguishing fixture"
else
    bad "Tcl: ResidueFlow or HetResidues differ from MOLE's derived order"
fi
sed 's/^/   /' "$TMP/out"

# ---- 9b. mixed-case chain identifiers ---------------------------------------
# MOLE pins the thread to InvariantCulture (Program.cs:35), so its OrderBy on
# ChainIdentifier COLLATES: "a" before "B", and "a" before "A". strcmp gives the
# opposite on both. Every other reference here has single-case chains, where the
# two rules agree, so the difference was invisible until this fixture.
#
# 1ERI with chain A renamed to a - non-symmetric (protein + DNA), unlike 1BL8,
# whose 4-fold symmetry absorbs any chain permutation. It discriminates in the
# cavity residue lists (Cavity.cs:288 orders them by chain) and in DepthLength,
# which moves at the 12th decimal because the pivot order feeds the incremental
# triangulation.
ERIMC="$DIR/fixtures/mole_atoms_1eri_mixedcase.txt"
RMC="$DIR/fixtures/mole_reference/1ERI_mixedcase"
if [ -x "$MOLE_ENGINE" ] && [ -f "$ERIMC" ] && [ -f "$RMC/cavities.xml" ]; then
    if "$MOLE_ENGINE" "$ERIMC" "$TMP/mc.txt" > "$TMP/mcout" 2>&1; then
        if python3 "$DIR/mole_cavity_truth.py" "$TMP/mc.txt" "$RMC/cavities.xml" \
                > "$TMP/out" 2>&1; then
            ok "mixed-case chains collate as MOLE's InvariantCulture does"
        else
            bad "mixed-case chain order differs from MOLE - see chain_cmp"
        fi
        sed 's/^/     /' "$TMP/out"
        # The other two OrderBy(ChainIdentifier) sites - ResidueFlow
        # (TunnelLining.cs:129) and HetResidues (Tunnel.cs:678). Both were
        # ordinal and are now routed through mole_chain_cmp.
        #
        # This fixture PASSES either way, kept for coverage against a real
        # protein rather than as a proof - 19 of its 50 layers hold both
        # chains, but the flow dedups first-seen across layers, so the
        # within-layer order never reaches the output. The distinguishing
        # regression is check 9a2 (mole_lining_regression_test.c/.tcl),
        # constructed from 1BL8's own first layer and a synthetic het table.
        if python3 "$DIR/mole_lining_truth.py" "$TMP/mc.txt" "$RMC" \
                > "$TMP/out" 2>&1; then
            ok "mixed-case ResidueFlow + layers agree with MOLE (not a discriminator)"
        else
            bad "mixed-case ResidueFlow or layers differ from MOLE"
        fi
        if python3 "$DIR/mole_het_residues.py" "$TMP/mc.txt" "$RMC" \
                > "$TMP/out" 2>&1; then
            ok "mixed-case HetResidues agree with MOLE (not a discriminator)"
        else
            bad "mixed-case HetResidues differ from MOLE"
        fi
    else
        bad "engine failed on the mixed-case fixture: $(tail -2 "$TMP/mcout")"
    fi
else
    echo "  SKIP  mixed-case fixture or MOLE reference missing"
fi

# ---- 10. the parameters that used to be hardcoded ---------------------------
# SurfaceCoverRadius, AutoOriginCoverRadius, MaxAutoOriginsPerCavity,
# BottleneckRadius and MaxTunnelSimilarity were literals in the engine until
# they were plumbed through. Defaults alone cannot show they are wired: the
# check has to run MOLE's own numbers at NON-default values.
#
# MaxTunnelSimilarity especially. At its 0.9 default the filter removes nothing
# on any structure available, so its removal path had never been compared with
# MOLE at all - only with its own suite at 0.5. At 0.5 on 1BL8 it takes 8
# tunnels down to 2, and MOLE agrees on which 2.
#
# BottleneckTolerance the same: 0.0 everywhere else, so the whole tolerance
# branch of FilterBottleneck (TunnelComputation.cs:40-59) was never compared
# with MOLE. At BottleneckRadius 1.6 on 1BL8 it takes 5 tunnels to 8 - the
# three extra ones (17.63, 19.17, 20.49) survive only via the tolerance.
BL8="$DIR/fixtures/mole_atoms_1bl8.txt"
if [ -x "$MOLE_ENGINE" ] && [ -f "$BL8" ]; then
    # Profiles, not layers: 1BL8's layer COUNTS differ from MOLE's for a
    # reason that has nothing to do with parameters - the circumcentre tie on
    # its 4-fold axis, Comparing profiles keeps this
    # check about the parameters.
    for v in "alt 2 --bottleneck=1.5 --maxsim=0.5" \
             "alt2 5 --cover=6 --autocover=15 --maxorigins=2" \
             "fbl 8 --fbl=1" \
             "btol 8 --bottleneck=1.6 --bottletol=3.0"; do
        set -- $v
        tag=$1; ntun=$2; shift 2
        R="$DIR/fixtures/mole_reference/1BL8_$tag"
        [ -f "$R/tunnels.xml" ] || { echo "  SKIP  no MOLE reference $R"; continue; }
        if "$MOLE_ENGINE" "$BL8" "$TMP/p_$tag.txt" 3.0 1.25 8 5.0 0.0 0 \
                "$@" > "$TMP/pout" 2>&1; then
            if python3 "$DIR/mole_ground_truth.py" "$TMP/p_$tag.txt" "$R" "$ntun" \
                    > "$TMP/out" 2>&1; then
                ok "non-default parameters match MOLE ($*)"
            else
                bad "non-default parameters differ from MOLE ($*)"
            fi
            sed 's/^/     /' "$TMP/out"
        else
            bad "engine failed at $*: $(tail -2 "$TMP/pout")"
        fi
    done
else
    echo "  SKIP  1BL8 fixture missing"
fi

# ---- 11. the ONE deliberate deviation from MOLE ------------------------------
# Everywhere else the bar is exact agreement. On 1MXT it is not, by decision:
# MOLE's similarity filter selects the 8.44 A tunnel and its removal loop then
# deletes that very tunnel (value-based List.Remove where identity is required).
# We emit what its filter selected. Pinned so nobody "fixes" us into matching
# the defect, and so this hear about it if upstream repairs theirs.
# See vmdhole/tests/fixtures/mole_reference/upstream_bug/.
MXT="$DIR/fixtures/mole_atoms_1mxt.txt"
if [ -x "$MOLE_ENGINE" ] && [ -f "$MXT" ]; then
    if "$MOLE_ENGINE" "$MXT" "$TMP/mxt.txt" > "$TMP/mxtout" 2>&1; then
        if python3 "$DIR/mole_upstream_deviation.py" "$TMP/mxt.txt" \
                > "$TMP/out" 2>&1; then
            ok "the documented 1MXT deviation is unchanged"
        else
            bad "the 1MXT deviation moved - read upstream_bug/ before changing it"
        fi
        sed 's/^/     /' "$TMP/out"
        # 1MXT is the ONLY fixture carrying hydrogens - 3696 of them - so
        # without this MOLE's backboneNames entry for "H" is never checked
        # against MOLE at all. It cannot be compared positionally, because the
        # removal defect above gives the two engines different tunnel SETS, so
        # the three tunnels they DO share are paired by length instead.
        REFMXT="$DIR/fixtures/mole_reference/1MXT"
        if [ -f "$REFMXT/tunnels.xml" ]; then
            if python3 "$DIR/mole_lining_truth.py" "$TMP/mxt.txt" "$REFMXT" \
                    --by-length > "$TMP/out" 2>&1; then
                ok "1MXT lining matches MOLE on the shared tunnels (hydrogens)"
            else
                bad "1MXT lining differs from MOLE on the shared tunnels"
            fi
            sed 's/^/     /' "$TMP/out"
        else
            echo "  SKIP  no 1MXT lining reference"
        fi
    else
        bad "engine failed on 1MXT: $(tail -2 "$TMP/mxtout")"
    fi
else
    echo "  SKIP  1MXT fixture missing"
fi

# ---- 12. the counterexample that decides the custom-exit architecture --------
# An exit that snaps ONLY to the SurfaceCavity (0.607 A) and misses every
# regular cavity (12.3 A+, against OriginRadius 5) still yields a MOLE tunnel,
# T1C0 8.82 A. A regular-cavity-only implementation returns nothing there, which
# is what rules that shortcut out. Not rare: of 40 sampled surface points on
# 1tqn, 17 produced a tunnel and every one was surface-only.
# The first three checks pin MOLE's reference so the fixture cannot rot; the
# fourth reports the engine, which is NOT IMPLEMENTED until the SurfaceCavity is
# searchable.
SEX="$DIR/fixtures/mole_reference/surface_exit"
if [ -f "$SEX/tunnels.csv" ]; then
    ORI2=$(awk '$6=="A" && ($7==308 || $7==309) {x+=$1;y+=$2;z+=$3;n++} \
               END{printf "%.6f %.6f %.6f", x/n, y/n, z/n}' "$FIX")
    "$MOLE_ENGINE" "$FIX" "$TMP/sx.txt" 3.0 1.25 8 5.0 0.0 0 $ORI2 5.0 \
        --exit=-22.841,-55.065,-20.445 --exitsonly=1 > "$TMP/sxout" 2>&1
    if python3 "$DIR/mole_surface_exit.py" "$SEX" "$TMP/sx.txt" > "$TMP/out" 2>&1; then
        ok "surface exit: we reproduce MOLE's SurfaceCavity tunnel"
    else
        bad "surface-exit tunnel differs from MOLE"
    fi
    sed 's/^/     /' "$TMP/out"
else
    echo "  SKIP  surface-exit reference missing"
fi

# ---- 13. paths: Dijkstra between two user points on the SurfaceCavity --------
# Complex.GetPaths. Both endpoints are given, so no origins and no openings, and
# the rules differ from a tunnel's: endpoints snap with GetTetrahedron (nearest
# member by centroid over the WHOLE cavity, not just boundary facets),
# CreatePath trims after the LAST non-boundary tetrahedron rather than at the
# first, requires tl >= 10 and max depth >= 6, and Type = Path skips the
# leading-radius trim in CalculateProfile.
PTH="$DIR/fixtures/mole_reference/paths"
if [ -x "$MOLE_ENGINE" ] && [ -f "$PTH/tunnels.csv" ]; then
    ORI3=$(awk '$6=="A" && ($7==308 || $7==309) {x+=$1;y+=$2;z+=$3;n++} \
               END{printf "%.6f,%.6f,%.6f", x/n, y/n, z/n}' "$FIX")
    if "$MOLE_ENGINE" "$FIX" "$TMP/path.txt" 3.0 1.25 8 5.0 0.0 0 \
            --path=$ORI3,-27.435,0.017,-11.724 > "$TMP/pout" 2>&1; then
        if python3 "$DIR/mole_ground_truth.py" "$TMP/path.txt" "$PTH" 1 \
                > "$TMP/out" 2>&1; then
            ok "paths match MOLE's own export (GetPaths)"
        else
            bad "path differs from MOLE"
        fi
        sed 's/^/     /' "$TMP/out"
    else
        bad "engine failed on the path run: $(tail -2 "$TMP/pout")"
    fi
else
    echo "  SKIP  paths reference missing"
fi

# ---- 14. the SurfaceCavity features in PURE TCL ------------------------------
# Custom exits and paths went into the C first, and the byte-identity test only
# exercises the DEFAULT path - a Tcl ignoring --exit and --path entirely would
# still pass it. The plugin falls back to Tcl when the binary is missing, so a
# user on that path would silently get no exits and no paths.
if [ -f "$PTH/tunnels.csv" ] && [ -f "$SEX/tunnels.csv" ]; then
    if timeout 300 tclsh "$DIR/test_mole_surface_tcl.tcl" "$FIX" "$SEX" "$PTH" \
            "$DIR/fixtures/mole_reference/mixed_exit" \
            > "$TMP/out" 2>&1; then
        ok "pure Tcl reproduces the surface-exit tunnel and the path"
    else
        bad "pure Tcl differs on the SurfaceCavity features"
    fi
    sed 's/^/     /' "$TMP/out"
else
    echo "  SKIP  surface-exit or paths reference missing"
fi

# ---- 15. circumcentre against MOLE's OWN measured value ----------------------
# Every other parity check generates its C reference from the currently compiled
# C and compares Tcl against it, so a matched revert in both would stay green;
# and the 1BL8 checks compare ROUNDED profiles, which cannot see a last bit.
# This pins SphereFromPoints to two circumcentres measured out of MOLE itself,
# for the tetrahedron whose vertex order decides 1BL8's layer boundaries.
if "$CC" -O2 $MOLE_FLAGS -I "$SRC" -o "$TMP/circ" \
        "$SRC/mole/mole_circumsphere_oracle.c" "$SRC/mole/mole_complex.c" "$SRC/mole/mole_rng.c" \
        "$SRC/voronoi/vor_delaunay.c" "$SRC/voronoi/vor_predicates.c" -lm 2>"$TMP/cerr"; then
    if "$TMP/circ" > "$TMP/out" 2>&1; then
        ok "circumcentre matches MOLE's own measured value"
    else
        bad "circumcentre differs from MOLE's own measured value"
    fi
    sed 's/^/     /' "$TMP/out"
else
    echo "  SKIP  circumsphere oracle did not build: $(tail -1 "$TMP/cerr")"
fi

# ---- 16. StrictInterior, against a MOLE rebuilt with it forced on -----------
# The one ComplexParameters field MOLE's CLI cannot reach. It was left unported
# on the grounds that nothing could validate it; that was wrong - forcing it
# true in a SEPARATE MOLE build validates it exactly like every other parameter.
# The branch is degenerate upstream (its prerequisite edge update is commented
# out), so it yields no cavities at all; the numbers that decide this check are
# therefore the SurfaceCavity's, which survive and GROW.
if [ -x "$MOLE_ENGINE" ] && [ -f "$BL8" ]; then
    for st in 0 1; do
        flag=""; [ "$st" = 1 ] && flag="--strict-interior=1"
        MOLE_SURFACE_DEBUG=1 "$MOLE_ENGINE" "$BL8" "$TMP/si_$st.txt" \
            3.0 1.25 8 5.0 0.0 0 $flag > "$TMP/si_$st.err" 2>&1
        ORI4=$(awk '$6=="A" && ($7==308 || $7==309) {x+=$1;y+=$2;z+=$3;n++} \
                   END{printf "%.6f %.6f %.6f", x/n, y/n, z/n}' "$FIX")
        "$MOLE_ENGINE" "$FIX" "$TMP/six_$st.txt" 3.0 1.25 8 5.0 0.0 0 \
            $ORI4 5.0 --exit=-22.841,-55.065,-20.445 --exitsonly=1 $flag \
            > "$TMP/sixout" 2>&1
    done
    if python3 "$DIR/mole_strict_interior.py" "$TMP/si_0.err" "$TMP/si_0.txt" \
            "$TMP/si_1.err" "$TMP/si_1.txt" "$TMP/six_0.txt" "$TMP/six_1.txt" \
            > "$TMP/out" 2>&1; then
        ok "StrictInterior matches MOLE, on and off"
    else
        bad "StrictInterior differs from MOLE"
    fi
    sed 's/^/     /' "$TMP/out"

    # And in pure Tcl, against the same MOLE numbers rather than against the C.
    if timeout 300 tclsh "$DIR/test_mole_strict_interior.tcl" "$BL8" \
            > "$TMP/out" 2>&1; then
        ok "pure Tcl reproduces MOLE's StrictInterior numbers"
    else
        bad "pure Tcl differs from MOLE under StrictInterior"
    fi
    sed 's/^/     /' "$TMP/out"
else
    echo "  SKIP  1BL8 fixture or engine missing"
fi

# ---- 17. the triangulation against MOLE'S OWN cells, ORDER included ---------
# Every other triangulation check compares a cell SET, which any correct
# Delaunay code passes. This compares the order of the four vertices WITHIN each
# cell and the order of the cells themselves against a dump taken out of MOLE.
# Neither is derivable from the geometry - both are the history of MOLE's
# incremental insertion, which is the whole reason mole_dh exists. Before it,
# 1BL8 reported 27 30 28 29 lining layers where MOLE reports 26 29 27 28.
TRI="$DIR/fixtures/mole_reference/triangulation"
if [ -x "$TMP/dhdump" ] || "$CC" -O2 $MOLE_FLAGS -I "$SRC" -o "$TMP/dhdump" \
        "$SRC/mole/mole_dh_dump.c" "$SRC/mole/mole_dh.c" "$SRC/mole/mole_complex.c" \
        "$SRC/mole/mole_rng.c" "$SRC/voronoi/vor_delaunay.c" "$SRC/voronoi/vor_predicates.c" \
        -lm 2>"$TMP/dherr"; then
    for pair in 1BL8:1bl8 1ERI:1eri 1MXT:1mxt 1TQN:1tqn; do
        nm=${pair%%:*}; fx=${pair##*:}
        F="$DIR/fixtures/mole_atoms_$fx.txt"
        [ -f "$TRI/$nm.cells" ] && [ -f "$F" ] || { echo "  SKIP  no $nm reference"; continue; }
        "$TMP/dhdump" "$F" > "$TMP/cells.txt" 2>/dev/null
        if python3 "$DIR/mole_triangulation_truth.py" "$TMP/cells.txt" \
                "$TRI/$nm.cells" > "$TMP/out" 2>&1; then
            ok "$nm triangulation matches MOLE cell for cell and slot for slot"
        else
            bad "$nm triangulation differs from MOLE"
        fi
        sed 's/^/     /' "$TMP/out"
    done
    # And the pure Tcl against the same reference, not merely against the C.
    F="$DIR/fixtures/mole_atoms_1bl8.txt"
    if [ -f "$TRI/1BL8.cells" ] && timeout 600 tclsh "$DIR/dh_cells.tcl" "$F" \
            > "$TMP/tcells.txt" 2>"$TMP/tcerr"; then
        if python3 "$DIR/mole_triangulation_truth.py" "$TMP/tcells.txt" \
                "$TRI/1BL8.cells" > "$TMP/out" 2>&1; then
            ok "pure Tcl reproduces MOLE's cell and vertex order too"
        else
            bad "pure Tcl triangulation differs from MOLE"
        fi
        sed 's/^/     /' "$TMP/out"
    else
        echo "  SKIP  Tcl triangulation dump failed: $(tail -1 "$TMP/tcerr" 2>/dev/null)"
    fi

    # Coplanar start: DHTriangulation.Init rejects a first cell with MinorsQ
    # below 1e-7 and swaps in a later vertex. This is the ONE place the port
    # cannot follow MOLE, and deliberately - MOLE picks the replacement with a
    # time-seeded `new Random()` constructed INSIDE the loop
    # (DHTriangulation.cs:104-113), so its own output is not reproducible here.
    # We take vertices 4, 5, ... in order instead.
    #
    # So the check is the two things that remain true: the path is reached, and
    # both engines walk it identically. A fixture that stopped being degenerate
    # would pass everything below while testing nothing, so the warning count is
    # asserted first.
    CP="$DIR/fixtures/mole_atoms_coplanar.txt"
    if [ -f "$CP" ]; then
        "$TMP/dhdump" "$CP" > "$TMP/cp_c.cells" 2>"$TMP/cp_err"
        nswap=$(grep -c "coplanar" "$TMP/cp_err" 2>/dev/null || echo 0)
        if [ "$nswap" -ge 1 ]; then
            ok "the coplanar-start path is reached ($nswap swaps)"
        else
            bad "the coplanar fixture no longer starts degenerate - it tests nothing"
        fi
        if timeout 300 tclsh "$DIR/dh_cells.tcl" "$CP" > "$TMP/cp_tcl.cells" 2>/dev/null \
                && [ -s "$TMP/cp_c.cells" ] && cmp -s "$TMP/cp_c.cells" "$TMP/cp_tcl.cells"; then
            ok "C and Tcl agree cell for cell through the coplanar start"
        else
            bad "C and Tcl diverge on the coplanar start"
        fi
    else
        echo "  SKIP  no coplanar fixture"
    fi
else
    echo "  SKIP  dh dump did not build: $(tail -1 "$TMP/dherr")"
fi

# ---- 18. 1BL8's own lining, which only became checkable with DH -------------
# This structure's lining had four spurious layer boundaries until MOLE's vertex
# order was reproduced, so there was nothing to pin: the suite carried 1BL8 for
# PROFILES only, and the divergence lived in a note. It is exact now, so it is a
# test. It is also the ONLY structure where the divergence ever appeared, which
# makes it the one that would go red first if the triangulation regressed in a
# way the cell digest somehow missed.
REFBL8="$DIR/fixtures/mole_reference/1BL8"
if [ -x "$MOLE_ENGINE" ] && [ -f "$BL8" ] && [ -f "$REFBL8/tunnels.xml" ]; then
    if "$MOLE_ENGINE" "$BL8" "$TMP/bl8.txt" > "$TMP/bl8out" 2>&1; then
        if python3 "$DIR/mole_ground_truth.py" "$TMP/bl8.txt" "$REFBL8" 8 \
                > "$TMP/out" 2>&1; then
            ok "1BL8 profiles match MOLE's own export (8 tunnels)"
        else
            bad "1BL8 profiles differ from MOLE"
        fi
        sed 's/^/     /' "$TMP/out" | tail -3
        if python3 "$DIR/mole_lining_truth.py" "$TMP/bl8.txt" "$REFBL8" \
                > "$TMP/out" 2>&1; then
            ok "1BL8 lining layers match MOLE - the divergence DH closed"
        else
            bad "1BL8 lining differs from MOLE"
        fi
        sed 's/^/     /' "$TMP/out" | grep -E "layers|weighted" | head -9
    else
        bad "engine failed on 1BL8: $(tail -2 "$TMP/bl8out")"
    fi
else
    echo "  SKIP  1BL8 default reference missing"
fi

# ---- 19. <HetResidues>, which was left unported for a WRONG reason ----------
# The stated reason was "empty on every reference, so unvalidatable". Checking
# rather than remembering: hem_origin carries HEM 508 A on three of four tunnels
# and 1ERI carries DT 9 B then DA 6 B + DA 7 B. Both are compared, and the
# checker refuses to credit an all-empty comparison.
if [ -x "$MOLE_ENGINE" ]; then
    FE2=$(awk '$8=="HEM" && $10=="FE" {print $1, $2, $3; exit}' "$FIX")
    if [ -n "$FE2" ] && [ -f "$REFHEM/tunnels.xml" ]; then
        "$MOLE_ENGINE" "$FIX" "$TMP/hh.txt" 3.0 1.25 8 5.0 0.0 0 \
            $FE2 12.0 > /dev/null 2>&1
        if python3 "$DIR/mole_het_residues.py" "$TMP/hh.txt" "$REFHEM" \
                > "$TMP/out" 2>&1; then
            ok "HetResidues match MOLE on the heme origin"
        else
            bad "HetResidues differ from MOLE on the heme origin"
        fi
        sed 's/^/     /' "$TMP/out"
    else
        echo "  SKIP  no heme reference for HetResidues"
    fi
    # 1KX5, the nucleosome: 21 of 60 tunnels carry het residues, up to six each,
    # which is far richer than either reference above. Paired by LENGTH because
    # the two engines differ on the tunnel SET here (57 against 60) - see
    #that divergence is NOT diagnosed.
    KX5="$DIR/fixtures/mole_atoms_1kx5.txt"
    REFKX5="$DIR/fixtures/mole_reference/1KX5"
    if [ -f "$KX5" ] && [ -f "$REFKX5/tunnels.xml" ]; then
        "$MOLE_ENGINE" "$KX5" "$TMP/kh.txt" > /dev/null 2>&1
        if python3 "$DIR/mole_het_residues.py" "$TMP/kh.txt" "$REFKX5" --by-length \
                > "$TMP/out" 2>&1; then
            ok "HetResidues match MOLE on the nucleosome (48 paired tunnels)"
        else
            bad "HetResidues differ from MOLE on 1KX5"
        fi
        grep -E "pair by length|at least one" "$TMP/out" | sed 's/^/     /'
    else
        echo "  SKIP  no 1KX5 reference for HetResidues"
    fi
    # WHY the profile-sphere half of FindHetResidues never fires. Deleting it
    # changes no answer anywhere, which looks exactly like a broken
    # transcription; this pins the geometry that makes it inert instead.
    if [ -n "$FE2" ]; then
        MOLE_HET_PROBE=1 "$MOLE_ENGINE" "$FIX" "$TMP/pp.txt" \
            3.0 1.25 8 5.0 0.0 0 $FE2 12.0 2>"$TMP/probe.log" >/dev/null
        if python3 "$DIR/mole_het_probe.py" "$TMP/probe.log" > "$TMP/out" 2>&1; then
            ok "the het sphere search is inert because Radius is surface-distance"
        else
            bad "the het sphere search now REACHES atoms - mole_lining.c's reasoning is stale"
        fi
        sed 's/^/     /' "$TMP/out"
    fi
    # Openings against MOLE's own, tetrahedron index for tetrahedron index. Only
    # possible because the triangulation reproduces MOLE's cell order.
    if [ -f "$KX5" ] && [ -f "$REFKX5/openings.txt" ]; then
        MOLE_OPENING_DEBUG=1 "$MOLE_ENGINE" "$KX5" "$TMP/ko.txt" \
            2>"$TMP/op.log" >/dev/null
        if python3 "$DIR/mole_openings_truth.py" "$TMP/op.log" \
                "$REFKX5/openings.txt" > "$TMP/out" 2>&1; then
            ok "cavity openings match MOLE index for index (19 cavities)"
        else
            bad "cavity openings differ from MOLE - check cavityGraph.Vertices order"
        fi
        sed 's/^/     /' "$TMP/out"
    else
        echo "  SKIP  no 1KX5 openings reference"
    fi
    # 1KX5's tunnel COUNT and length multiset. It was 57 against 60 and is now
    # 60 with 59 of 60 lengths matching. The ONE that differs is the documented
    # upstream removal defect appearing a second time - the two candidates in
    # cavity 18 have IDENTICAL linings, so List<Tunnel>.Remove cannot tell them
    # apart. Pinned so the two fixes that got it here - the opening order and
    # the accumulated Distance - cannot silently come undone.
    if [ -f "$KX5" ] && [ -f "$REFKX5/tunnels.csv" ]; then
        "$MOLE_ENGINE" "$KX5" "$TMP/kt.txt" > /dev/null 2>&1
        got=$(grep -c '^T ' "$TMP/kt.txt")
        want=$(( $(wc -l < "$REFKX5/tunnels.csv") - 1 ))
        # .NET's ToString("0.00") rounds half AWAY FROM ZERO; Python's %.2f rounds
        # half to even. 24.5250 is exactly a midpoint, so the wrong rounding here
        # invents a disagreement that is not in the engine - it did, once.
        match=$(python3 -c "
from collections import Counter
from decimal import Decimal, ROUND_HALF_UP
def net2(x): return str(Decimal(repr(x)).quantize(Decimal('0.01'), rounding=ROUND_HALF_UP))
o=Counter(net2(float(l.split()[3])) for l in open('$TMP/kt.txt') if l.startswith('T '))
m=Counter(l.strip().split(',')[1] for l in list(open('$REFKX5/tunnels.csv'))[1:])
print(sum((o&m).values()))")
        if [ "$got" = "$want" ] && [ "$match" -ge 59 ]; then
            ok "1KX5: $got tunnels (MOLE $want), $match lengths match"
        else
            bad "1KX5 regressed: $got tunnels vs $want, $match lengths match"
        fi
    else
        echo "  SKIP  no 1KX5 tunnels reference"
    fi
    if [ -f "$ERI" ] && [ -f "$REFERI/tunnels.xml" ]; then
        "$MOLE_ENGINE" "$ERI" "$TMP/eh.txt" > /dev/null 2>&1
        if python3 "$DIR/mole_het_residues.py" "$TMP/eh.txt" "$REFERI" \
                > "$TMP/out" 2>&1; then
            ok "HetResidues match MOLE on the protein-DNA complex"
        else
            bad "HetResidues differ from MOLE on 1ERI"
        fi
        sed 's/^/     /' "$TMP/out"
    else
        echo "  SKIP  no 1ERI reference for HetResidues"
    fi
fi

# ---- 22. a custom exit ALONGSIDE the regular openings -----------------------
# Every other custom-exit check runs with UseCustomExitsOnly. Without it,
# GetTunnels builds `sources` as the origin's cavity CONCATENATED with the
# SurfaceCavity and runs FilterTunnels over the COMBINED list - so the surface
# tunnel and the cavity's own tunnels compete for similarity. Gating the surface
# search on exits-only lost MOLE's 8.82 A tunnel entirely, and filtering the two
# groups apart kept a 13.82 A one MOLE removes. This reference has both.
REFMIX="$DIR/fixtures/mole_reference/mixed_exit"
if [ -x "$MOLE_ENGINE" ] && [ -f "$REFMIX/tunnels.csv" ]; then
    ORI5=$(awk '$6=="A" && ($7==308 || $7==309) {x+=$1;y+=$2;z+=$3;n++} \
               END{printf "%.6f %.6f %.6f", x/n, y/n, z/n}' "$FIX")
    "$MOLE_ENGINE" "$FIX" "$TMP/mix.txt" 3.0 1.25 8 5.0 0.0 0 \
        $ORI5 5.0 --exit=-22.841,-55.065,-20.445 > /dev/null 2>&1
    # IN ORDER, not as a sorted set: MOLE's TunnelComparer is
    # (Cavity.Id, Length) and the SurfaceCavity is Id 0, so its tunnel comes
    # FIRST. Our sort used to run before the surface branch appended, which put
    # it last - the set matched and the order did not, which a sorted
    # comparison would never have shown.
    got=$(awk '$1=="T"{printf "%.2f\n",$4}' "$TMP/mix.txt" | tr '\n' ' ')
    want=$(tail -n +2 "$REFMIX/tunnels.csv" | cut -d, -f2 | tr '\n' ' ')
    if [ "$got" = "$want" ]; then
        ok "custom exit + regular openings match MOLE, in order ($want)"
    else
        bad "mixed custom-exit run differs: got [$got] want [$want]"
    fi
else
    echo "  SKIP  no mixed custom-exit reference"
fi

# ---- 23. every checked-in C test must still COMPILE ------------------------
# Two of them had gone stale against a changed mole_filter_bottleneck signature
# and nobody noticed, because the suite only builds the ones it runs.
cfail=""
for t in mole_tunnel_test mole_auto_test mole_origin_test mole_cavity_test \
         mole_tunnel_dump mole_complex_dump mole_dt_dump mole_predicate_cases; do
    [ -f "$SRC/$t.c" ] || continue
    "$CC" -O2 $MOLE_FLAGS -I "$SRC" -o "$TMP/ct_$t" "$SRC/$t.c" \
        "$SRC/mole/mole_lining.c" "$SRC/mole/mole_tunnel.c" "$SRC/mole/mole_complex.c" \
        "$SRC/mole/mole_dh.c" "$SRC/mole/mole_rng.c" "$SRC/voronoi/vor_delaunay.c" \
        "$SRC/voronoi/vor_predicates.c" -lm 2>/dev/null || cfail="$cfail $t"
done
if [ -z "$cfail" ]; then ok "every checked-in C test compiles"
else bad "C tests no longer compile:$cfail"; fi

# ---- 24. the VMD adapter's atom table must carry altLoc and insertion code --
# _tunnel_atoms_mole is the ONLY producer in the shipped plugin - the fixtures
# come from the extractors, so a schema regression there is invisible to every
# other check. mole_pivot_order keys residues on (chain, number, insertion code)
# and groups atoms by altLoc, so dropping columns 11-12 changes the pivot order
# and the triangulation with it.
# The adapter itself is RUN by test_adapter_schema.sh, which needs VMD; a grep
# for the format string here could not see altLoc and insertion code swapped.
# What this group can check without VMD is the committed fixtures' schema.
ncol=$(awk 'NR==1{print NF}' "$DIR/fixtures/mole_atoms_1mxt.txt")
if [ "$ncol" = "12" ]; then ok "the committed fixtures carry 12 columns"
else bad "fixture schema is $ncol columns, not 12"; fi

# ---- 25. a TWO-CAVITY origin with a custom exit -----------------------------
# MOLE calls GetOrigin per cavity and ComputeTunnels per origin, with `sources`
# = the cavities holding that origin CONCAT the SurfaceCavity, so the similarity
# group is per ORIGIN across its cavities plus the surface. Our C defers the
# filter and runs it over the whole result array when a custom exit is present,
# which is a different grouping. This is the case that exercises it: the heme
# origin snaps into cavities 1 and 7, and a custom exit is supplied.
#
# It PASSES on the current grouping - MOLE reports the same four tunnels with
# and without the exit here, so the difference does not manifest. Kept because
# it pins the two-cavity-plus-exit path, and noted in as
# NOT the discriminating case the grouping question still needs.
REFHM="$DIR/fixtures/mole_reference/hem_mix"
if [ -x "$MOLE_ENGINE" ] && [ -f "$REFHM/tunnels.csv" ]; then
    FE3=$(awk '$8=="HEM" && $10=="FE" {print $1, $2, $3; exit}' "$FIX")
    "$MOLE_ENGINE" "$FIX" "$TMP/hm.txt" 3.0 1.25 8 5.0 0.0 0 \
        $FE3 12.0 --exit=-22.841,-55.065,-20.445 > /dev/null 2>&1
    # IN ORDER and unsorted: MOLE's ids carry the cavity (T4C7 here), and its
    # comparator is (Cavity.Id, Length), so the printed order IS the provenance.
    # Sorting the lengths discards exactly the information this check is for.
    got=$(awk '$1=="T"{printf "%.2f\n",$4}' "$TMP/hm.txt" | tr '\n' ' ')
    want=$(tail -n +2 "$REFHM/tunnels.csv" | cut -d, -f2 | tr '\n' ' ')
    if [ "$got" = "$want" ]; then
        ok "two-cavity origin + custom exit matches MOLE, in order ($want)"
    else
        bad "two-cavity custom-exit run differs: got [$got] want [$want]"
    fi
else
    echo "  SKIP  no two-cavity custom-exit reference"
fi

echo "  ---- $pass passed, $fail failed"

# The real gate, as the LAST command so every section above counts.
[ "$fail" -eq 0 ]
