# The Tcl exact predicates must agree with the C ones on every case, including
# the constructed coplanar and cospherical ones where a sign of exactly 0 is the
# right answer and a floating-point implementation would not give it.
#
# The "Q" rows check quantisation, which the predicate rows cannot: they start
# from integers, so vp_quant's round-half-away-from-zero branch never runs. That
# branch is reachable only from a scaled value landing exactly on a half step,
# which no real coordinate does after MOLE's jitter - so the cases are
# constructed, and the test asserts the branch was actually taken on both signs
# rather than assuming it.
#
# Cases are generated by the C itself (see test_mole_tcl_port.sh), so this is a
# direct cross-check of the two implementations rather than of either against a
# model.
# The engine is inlined in vmdhole.tcl now (one shipped script + the
# compiled binaries), so this extracts it instead of sourcing modules.
source [file join [file dirname [file normalize [info script]]] mole_tcl_engine.tcl]

set SCALE 100000.0

set cases [lindex $argv 0]
set f [open $cases r]
set n 0; set bado 0; set bads 0
set nq 0; set badq 0; set halfpos 0; set halfneg 0
while {[gets $f line] >= 0} {
    if {[string trim $line] eq ""} continue
    if {[lindex $line 0] eq "Q"} {
        lassign $line _ x want half
        set got [::VMDHole::Mole::quant $x $SCALE]
        if {$got != $want} {
            incr badq
            if {$badq <= 3} { puts "  quant differs on $x: got $got want $want" }
        }
        if {$half} { if {$x < 0} { incr halfneg } elseif {$x > 0} { incr halfpos } }
        incr nq
        continue
    }
    lassign $line ax ay az bx by bz cx cy cz dx dy dz ex ey ez wo ws
    set go [::VMDHole::Mole::orient3d $ax $ay $az $bx $by $bz $cx $cy $cz $dx $dy $dz]
    set gs [::VMDHole::Mole::insphere $ax $ay $az $bx $by $bz $cx $cy $cz $dx $dy $dz $ex $ey $ez]
    if {$go != $wo} { incr bado; if {$bado <= 3} { puts "  orient3d differs: got $go want $wo" } }
    if {$gs != $ws} { incr bads; if {$bads <= 3} { puts "  insphere differs: got $gs want $ws" } }
    incr n
}
close $f
puts [format "  %-52s %s" "orient3d matches C on $n cases" [expr {$bado==0 ? "PASS" : "FAIL ($bado differ)"}]]
puts [format "  %-52s %s" "insphere matches C on $n cases" [expr {$bads==0 ? "PASS" : "FAIL ($bads differ)"}]]
puts [format "  %-52s %s" "quant matches C on $nq cases" [expr {$badq==0 ? "PASS" : "FAIL ($badq differ)"}]]
set tie [expr {$halfpos > 0 && $halfneg > 0}]
puts [format "  %-52s %s" "half-step tie broken away from zero, both signs" \
      [expr {$tie ? "PASS ($halfpos +ve, $halfneg -ve)" : "FAIL (never exercised)"}]]
exit [expr {($bado||$bads||$badq||!$tie) ? 1 : 0}]
